### ISSUE TITLE
60% of Aligned Reads Was not Assigned to Transcript

### ISSUE THREAD

**Issue by jennLiang1** [ablab/IsoQuant#100]
Hi,

I input a bam file of aligned reads to IsoQuant (aligned with minimap2). There are 5517640 aligned reads in the input, but only 2121243 reads (~40%) are assigned with gene isoforms by IsoQuant. Any suggestions on possible causes for the other ~60% of reads left unassigned?

Below is the command I used. 
``` python
isoquant.py --data_type ont -r GRCh38.primary_assembly.genome.chrOnly.fa -g gencode.v37.annotation.gtf --complete_genedb --bam RNAetcclean.bam --stranded none -p HCT116_hg38_default --check_canonical -t 48 --matching_strategy default --model_construction_strategy default_ont
``` 

 Thank you!

**Comment by andrewprzh** [comment]
Dear @jennLiang1 

I see one BAM file processed with `Total alignments processed: 2121243`
Could check you BAM file (e.g. with samtools flagstat)? I don't see where the number 5517640 comes from :)

I also see a bug at the end of the log. This bug is fixed in the master branch and will be fixed in the next release.

Best
Andrey

**Comment by andrewprzh** [comment]
Please, reopen if you still have questions.
