### ISSUE TITLE
Many reads assigned but with zero counts. Weird results

### ISSUE THREAD

**Issue by biozhangzhou** [ablab/IsoQuant#117]
Hello,

I have three replicates of ONT cDNA sequencing files. A lot reads of them have assigned to a lnc gene, but the gene counts in one sample was zero. Why it happens ? 
![image](https://github.com/ablab/IsoQuant/assets/42492970/e83beff6-6bb6-4ff9-a764-87543f41953c)

Thanks,
Zhou

**Comment by andrewprzh** [comment]
Dear @biozhangzhou 

Could you please check the assignment type of reads assigned to these genes? By default, only unique assignments are used in quantification.
To change counting strategy you may use `--transcript_quantification` and `--gene_quantification` options.

Best
Andrey

**Comment by biozhangzhou** [comment]
Dear Andrey:
The sample with zero tpm value do have many unique reads. So it's really weird.
![image](https://github.com/ablab/IsoQuant/assets/42492970/db0fe99a-20a4-466f-a8a3-993a38e9ee09)

Best
Zhou

**Comment by andrewprzh** [comment]
Dear @biozhangzhou 

Indeed, looks odd. Could you send me just a small fragment of your BAM file (i.e. via email)? Privacy is guaranteed. 

Best
Andrey

**Comment by andrewprzh** [comment]
Dear @biozhangzhou 

I now realized that if a transcript is spliced, it must have at least on spliced read assigned to it to deemed as expressed. Otherwise it is not reported in the count table even if it has a lot of unique, but non-spliced alignments. This check is done since it looks quite suspicious for a spliced transcript to have 0 spliced alignments. At the same time, mono-exonic alignments have a higher false-positive rate.

Could you please check if it's the case?

Best
Andrey

**Comment by biozhangzhou** [comment]
Dear Andrey:

Very grateful for your continuous help and sorry for failing to respond. I have actually deleted that results and cannot reproduce that weird results now.  Everything seems to be going well, but I will keep your advice in mind and give you feedback when I meet familiar problems.

Best
Zhou

**Comment by andrewprzh** [comment]
@biozhangzhou 

Thanks for getting back, it took me a while to realize.  

Best
Andrey
