### ISSUE TITLE
Reusing reference index

### ISSUE THREAD

**Issue by andyjslee** [ablab/IsoQuant#132]
I see that Isoquant generates quite a large `.db` file from the reference annotation `GTF` file. What is the best way to reuse the same reference index for another dataset? Thank you in advance!

**Comment by andrewprzh** [comment]
@andyjslee 

You can provide .db file using the same option `--genedb`. Moreover, if you keep it in the previous output folder, the next run on the same machine and by the same user will automatically detect .db file.

Best
Andrey

**Comment by andyjslee** [comment]
@andrewprzh thank you for your prompt reply.

If I (1) supply a different FASTQ list file (i.e. a different dataset with different samples), (2) reuse the same `.db` file as you described above, and (3) designate the same output path, wouldn't the existing outputs be rewritten? How can I reuse the same `.db` file but be able to supply different samples each time while preserving the outputs from the earlier run? Thank you for your help.

**Comment by andrewprzh** [comment]
Dear @andyjslee 

If you specify the same output folder, the .db file should not be overwritten, even if the .db  file is in that folder. However, output prefix (-p option) should be different to keep you previous results. Otherwise, output subfolder will be overwritten.

Nonetheless, I suggest using another output folder to be safe.

Best
Andrey
