### ISSUE TITLE
Isoquant  on Single-cell Long Read Data

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#136]
Hello, I have a doubt, I used the following 2 commands to run and found that for new transcript identification is not the same situation

isoquant  --data_type nanopore  --bam_list sample_list.txt --read_group tag:NB --complete_genedb --genedb ${gtf} --reference ${ref} --output ${outdir}/01.isoquant_merge --sqanti_output --count_exons --threads 20  --check_canonical --force --clean_start
 The new transcripts produced by this command have particularly little overlap between different bam
sample_list.txt
<img width="304" alt="image" src="https://github.com/ablab/IsoQuant/assets/94769806/c8ed1294-a970-4f83-83f1-cd30ea7541c8">

isoquant  --data_type nanopore  --bam merge_bam--read_group tag:CB --complete_genedb --genedb ${gtf} --reference ${ref} --output ${outdir}/01.isoquant_merge --sqanti_output --count_exons --threads 20  --check_canonical --force --clean_start
 
merge_bam : merges the bam files above. CB:sample_name +NB
There is a lot of overlap between new transcripts of this command produced in different samples

thanks～

**Comment by andrewprzh** [comment]
Dear @dawangran 

I think this can be expected. When processing multiple files, IsoQuant performs additional check when reporting transcript models: a transcript should be supported by reads from at least 2 different files. Transcripts supported only by reads from a single sample/replica a considered to be unreliable. 

However, when using read alignment tag, this check is not performed because different read tags can have different meanings, e.g. cell barcodes or cell types (and IsoQuant does not know what is the meaning of the tag). 

Best
Andrey

**Comment by dawangran** [comment]
Thank you very much for your reply, but I still have a question, the first task I ran, detected new transcripts, there was very little overlap in the various samples, but when I used the second command, there was a lot of overlap.
Supplement: The first is multiple bam files and the second is to merge these bam files. Both have alignment tag enabled, so in theory, they should all be consistent.

**Comment by andrewprzh** [comment]
@dawangran 

Sorry, I didn't get the entire question the first time.
A couple of questions. What is tag:NB, name of the BAM file? How do you measure overlaps between samples?

I agree, merged BAM file with tag VS multiple BAM files should provide similar, if not identical results.

**Comment by andrewprzh** [comment]
Please, re-open the issue in there are still any questions. Closing for now as outdated.
