### ISSUE TITLE
read assignments

### ISSUE THREAD

**Issue by zpliu1126** [ablab/IsoQuant#137]
Dear Andrey,
After quantifying transcripts with isoquant successfully. I want to perform saturation curve analysis of the detected transcripts using long reads data. I checked the match of each read and transcript under the file `SAMPLE_ID.transcript_model_reads.tsv` . Surprisingly, many reads (48.7%, 28350326 ) were marked `*` . Is this ratio too high?

Below are the statistics from my data。

![image](https://github.com/ablab/IsoQuant/assets/39325949/ae81cd22-54a9-4ab3-b827-1f54bc0feeff)

Command line :

```bash
    isoquant.py  -d nanopore \
                --reference  IsoformAnnotation/D5/D5.chr.fa \
                --index  D5/D5.chr_k14_idx \
                --genedb  D5/D5_final_gene.chr.db \
                --prefix D5  \
                --output IsoQuant/D5_leaf/  \
                --report_novel_unspliced true \
                --sqanti_output \
                --genedb_output IsoformAnnotation/D5 \
                --fastq D3/pass.fq.gz D4/pass.fq.gz \
                --labels  Rep1 Rep2  \
                --threads 20 
```

Best
zpliu

**Comment by andrewprzh** [comment]
Dear @zpliu1126 

I cannot say for sure what percentage can be considered as "normal", depends on the data a lot. But I think it's ok that quite some reads don't contribute to any reported transcripts and thus marked with `*`. So I'd say it looks fine. 

If you need double check counts for novel transcripts, you can re-run IsoQuant using the same reads and providing `.extended_annotation.gtf` via `--genedb` (and setting `--no_model_construction`). If you are interested only in counts for reference genes/transcripts - you can also use `transcript_counts.tsv`.

Also, there is known issue with IsoQuant missing some read assignments during transcript model construction, but it typically affects a rather small portion of reads. In any case it will be fixed in the next release.  

Best
Andrey

**Comment by zpliu1126** [comment]
Hi~  Andrey

I have a question: Is IsoQuant sensitive to the quality of reference gene annotation? As mentioned in the README, reference gene annotation can provide accurate. The reference annotations I use are based on the short-reads annotations. I was surprised that so many read alignments (40%~60%) were classified as "*". Maybe my next step should be to check how many long reads are in these read alignmen.

> Reference gene annotation is not mandatory, but is likely to increase precision and recall. It can be provided in GFF/GTF format (can be gzipped). In this case it will be converted to gffutils database. Information on converted databases will be stored in your ~/.config/IsoQuant/db_config.json to increase speed of future runs. You can also provide gffutils database manually. Make sure that chromosome/scaffold names are identical in FASTA file and gene annotation.

Best 
zpliu

**Comment by zpliu1126** [comment]
Hi~ Andrey<br />I'm comparing transcriptome differences between two species. Considering that such a large proportion of long reads are marked with “*” and the proportion in the two species differs greatly, **I'm wondering if this was related to reference annotated gff3**. I ran IsoQuant multiple times from the following aspects and compared the proportion of long reads with the marker "\*":

1. raw long reads or clip by pychopper
2. used reference annotated gff or not

First I used `samtools flagstat` to check the alignment of minimap2. Sequence alignment was good in both species S1 and S2.<br />**Table 1. Sequence alignment statistics.**

| **Alignment**<br />**statistics** | **S1_rep1**<br />**(raw reads)** | **S1_rep2**<br />**(raw reads)** | **S1_rep1**<br />**(pychopper clipped)** | **S1_rep2**<br />**(pychopper clipped)** | **S2_rep1**<br />**(raw reads)** | **S2_rep2 **<br />**(raw reads)** | **S2_rep1**<br />**（pychopper clipped）** | **S2_rep2**<br />**（pychopper clipped）** |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| QC pass | 32445835 | 30686552 | 25239521 | 24342005 | 52400816 | 55623308 | 41000880 | 43828116 |
| secondary  | 5357186 (16.5%) | 4626986 <br />(15.07%） | 3214061<br />(12.73%) | 2753497<br />(11.31%) | 18126052 (34%) | 19798912 (35.5%) | 12921597<br />(31.51%) | 14248543<br />(32.51%) |
| supplementary | 1117189 | 1021235 | 329219 | 344468 | 1433006 | 1489472 | 400134 | 450518 |
| mapped | 31874320 (98.24%) | 30221910 (98.49%) | 24732786<br />(97.99%) | 23909981<br />(98.23%) | 51949972<br /> (99.14%) | 55078365 <br />(99.02%) | 40620791<br />（99.07%） | 43368060<br />（98.95%） |


**Table 2. Clipped read statistics (pychopper).**

| **long read Class** | **S1_rep1** | **S1_rep2** | **S2_rep1** | **S2_rep2** |
| --- | --- | --- | --- | --- |
| Primers_found reads | 21778161 | 21298229 | 27767152 | 29233643 |
| Unusable reads | 4225148 (16%) | 3785816 (15%) | 5165654 (15%) | 5191486 (15%) |

Next, I performed IsoQuant analysis on the raw and pychopper clipped long reads by using reference annotated gff or not, in respectively.  When S1 and S2 were analyzed using reference annotated gff, 48.78% and 60.9% of long reads were discarded. It seems like the long read data I sequenced is mostly meaningless. But when I don't use reference annotated gff, the proportion of discarded long reads in S1 and S2 is close (33% vs 37%). **Could the difference in quality of reference annotations between S1 and S2 lead to such a large difference in the proportion of discarded reads in the two species**? 

**Table 3. Statistics for IsoQuant.**

| **Read stat** | S1<br />(raw && reference) | S1<br />(clipped && reference) | S1<br />(raw && no reference) | S1<br />(clipped && no reference) | S2<br />(raw && reference) | S2<br />(clipped && reference) | S2<br />(raw && no reference) | S2<br />(clipped && no reference) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| read assignments | 53580602 | 44179181 | 52486732 | 43351467 | 90817238 | 73922584 | 64385995 | 54560782 |
| polyA tail detected | 45764490 | 17156890 | 45297545 | 17434661 | 74290886 | 22635663 | 57506031 | 22317807 |
| unique | 11212450 | 16580266 | - | - | 550659 | 720583 | -<br /> | - |
| unique_minor_difference | 956979 | 1807813 | - | - | 491106 | 487262 | - | - |
| inconsistent | 32021303 | 19084654  | - | - | 54690457 | 45587741 | - | - |
| ambiguous | 169889 | 148336 | - | - | 143001 | 98246 | - | - |
| noninformative | 9109361 | 6326705 | - | - | 34718992 | 26413134 | - | - |
| intergenic | 110620 | 231407 |  52486732 | 43351467 | 223023 | 615618 | 57506031 | 54560782 |
| read support isofrom model | 29764248 | 33061037 | 42075195 | 47178668 | 35143400 | 41924132 | 46399336 | 61262636 |
| **read marked *** | 28350326 (**48.78%**) | 16118579 (**32.77%**) | 21029475 <br />(**33%**) | 11316637 (**19.3%**) | 54955274（**60.9%**） | 42369305<br />(**50%**) | 28027044 <br />(**37%**) | 14782833 <br />(**19%**) |

**Comment by andrewprzh** [comment]
@zpliu1126 

>Is IsoQuant sensitive to the quality of reference gene annotation? 

Yes, quite sensitive. IsoQuant assumes reference transcripts are correct (e.g. GENCODE human or mouse annotation level correctness). If you have doubts - I suggest trying IsoQuant in annotation-free mode.

Regarding the read statistics.

1. I see S2 has ~2.5 times more secondary alignments compared to S1, why might that happen? I think I can be related to read assignment stats too.
2. It seems pychopper removes unreliable reads, that are otherwise are treated as unreliable by IsoQuant and are not assigned.
3. In annotation-free mode, IsoQuant uses some additional filters to ignore unreliable alignments (e.g. low MAPQ). The total number of assignments in annotation-free mode is lower, especially for S2. But the percentage of reads marked with * is lowers, so it seems that meaningful assignments are kept.

>Could the difference in quality of reference annotations between S1 and S2 lead to such a large difference in the proportion of discarded reads in the two species?

I think yes. It also seems that reference genome qualities are different too, is it possible?

Best
Andrey

**Comment by zpliu1126** [comment]
> I think yes. It also seems that reference genome qualities are different too, is it possible?

yes, I already have a better understanding of the results I'm getting. Thank you very much for developing such a useful tool.

Best
zpliu
