### ISSUE TITLE
Too many WARNING, for excemple:  WARNING - Malformed transcript mRNA_23979 has no exons

### ISSUE THREAD

**Issue by biochristmas** [ablab/IsoQuant#143]
Dear @andrewprzh, When I runing  isoquant.py, i got many WARNING,  I wanted to inquire about a potential issue that may affect the final output of the GTF file. I am wondering if you are aware of the underlying reason causing this issue.
![warning](https://github.com/ablab/IsoQuant/assets/107186260/e6b82713-7a3a-41e8-b6f0-f13d59087f99)
This is my input files and outfile:
[Files.zip](https://github.com/ablab/IsoQuant/files/14000634/Files.zip)
Best wish.

**Comment by andrewprzh** [comment]
Dear @biochristmas 

Regarding the first question. It seems like gffutils does something weird during conversion on your GTF to .db. Could you try changing all 'mRNA' entries to 'transcript' (i.e. in column 3 of your GTF)? I'll also try to get more insights.

With respect to the second question. Yes, the problem can directly connected by the first issue. But as I mentioned in another thread, there is a minor flaw in IsoQuant that will be fixed in the next release.

Best
Andreu

**Comment by biochristmas** [comment]
Dear @andrewprzh,
Thank you for your prompt reply. I replaced 'mRNA' with 'transcript' and successfully resolved the warning. I am looking forward to your new version to solve my urgent problem.

**Comment by andrewprzh** [comment]
New [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0) is finally out, so you can give it a try. It now implements additional GTF consistency checks.
Please, re-open if you encounter similar issues.
