### ISSUE TITLE
Question exon/intron counts

### ISSUE THREAD

**Issue by dawangran** [ablab/IsoQuant#160]
Hello, I have a question, would like to consult. What is the meaning of include_counts and exclude_counts in *exon_counts.tsv and *intron_counts.tsv?
Is the sum of include_counts and exclude_counts unequal for introns or exons of the same gene_id? I thought it was supposed to be equal. What is the cause of this.
![image](https://github.com/ablab/IsoQuant/assets/94769806/b98a7db7-dbab-471a-93cc-4c5caa2f283c)
17155 + 1112 != 16578 + 1393 ?

**Comment by andrewprzh** [comment]
@dawangran 

Yes, these sums should not be equal in general case. The main reason is that if an exon (or intron) is located outside of a read alignment, it is not counted neither as excluded nor included, simply because the read can be truncated and there is not enough information.

For example 

[ 1 ] ---- [ 2 ]
[ 1 ] -------------- [ 3 ]
[ 1 ] ---- [ 2 ] --- [ 3 ]
Isoform 1: 2 reads
Isoform 2: 1 read
Isofrom 3: 0 reads

Exon 1: 3 / 0
Exon 2: 2 / 1
Exon 3: 1 / 0

In general case it is not possible to distinguish whether reads from isoform 1 originate from isoform 1 or isoform 3, thus we cannot say that they "exclude" exon 3.

Best
Andrey
