### ISSUE TITLE
About poly_requirement option

### ISSUE THREAD

**Issue by hyeon9** [ablab/IsoQuant#173]
Hi developers,

Thank you for development of shiny tool!
Now I'm applying  IsoQuant to my pacbio FL data, as you already know.
Standard pacbio processing trim poly A tail, so that IsoQuant found only few transcripts in output file.
To avoid this situation, I applied a "--poly_requirement never" option, but it showed this error.
"isoquant.py: error: unrecognized arguments: --polya_requirement never"
My iso-quant version is v.3.3.1

Thank you,
Hyeongu

**Comment by andrewprzh** [comment]
Dear @hyeon9 

This option is new and will be released soon in IsoQuant 3.4. I have merged this change into master branch just yesterday and that's why it is now visible in the manual. 

If you reads have no polyA tails, IsoQuant 3.3.1 with automatically set `polya_requirement never` internally and polyA tails will be required for transcript discovery.

I'll let you know when the new version is released!

Best
Andrey

**Comment by hyeon9** [comment]
Thank you for your fast and kind response :)
Hyeongu

**Comment by andrewprzh** [comment]
Finally, [IsoQuant 3.4](https://github.com/ablab/IsoQuant/releases/tag/v3.4.0) is out!

**Comment by hyeon9** [comment]
Thank you for let me know!
But, may I ask question? 
I definitely expected that my count matrix will have integer counts, but I found that there are few float counts.
Should I do rounding off for these float counts?

Thank you so much!!

**Comment by andrewprzh** [comment]
In IsoQuant 3.3.1 ambiguous reads were "split" between different features. 
If a read is ambiguously assigned to two distinct transcripts, it adds 0.5 to both.
I'd say it's pretty safe to round those numbers.

In version 3.4 only unique read are used by default and thus counts are expected to be integers.

This behavior can be controlled with `--transcript_quantification` and `--gene_quantification` options.

Best
Andrey
