### ISSUE TITLE
TPM value difference of a sample between runs

### ISSUE THREAD

**Issue by abhijitcbio** [ablab/IsoQuant#181]
Hi, Thanks for developing such a nice and easy to use tool. 

I am currently analyzing a bunch of ONT long-read samples and trying to map them using isoquant. 

I have two different cell lines Nalm6 and Jurkat with multiple conditions. 

In the first run, I am processing only the Nalm6 samples and in the second run, I am running isoquant with both Nalm6 and Jurkat files together.      

However, in the first run let's say for the "SON" gene I am getting the following TPM value for one of the Nalm6 condition 
```
transcript_id	NALM6_EV
ENST00000356577	11.337801
ENST00000381679	1.223618
transcript19873.21.nnic	0.33119
```
But for the second run, I am getting the following values for the same sample - 
```
transcript_id	NALM6_EV
ENST00000300278	0.971314
ENST00000356577	0.311926
ENST00000381679	1.101613
ENST00000436227	6.580062
transcript22541.21.nnic	0.311926
```
I am attaching the TPM table of SON transcripts across samples for the two runs. 
[Expression_Difference.xlsx](https://github.com/ablab/IsoQuant/files/15211923/Expression_Difference.xlsx)

I am using the `.transcript_model_grouped_tpm.tsv` file to get the values. 

For your reference, I am attaching the log files from the two runs.  

[NALM6_JURKAT.isoquant.log](https://github.com/ablab/IsoQuant/files/15211955/NALM6_JURKAT.isoquant.log)
[NALM6_all_conditions.isoquant.log](https://github.com/ablab/IsoQuant/files/15211956/NALM6_all_conditions.isoquant.log)

Let me know if I am making any mistake in running the code. 

Looking forward to your reply!

**Comment by andrewprzh** [comment]
Dear @abhijitcbio 

I don't see any errors in your command lines. Here are a few comments:

- If you are looking for expression of reference transcripts, I'd suggest using `*.transcript_tpm.tsv`. `transcript_model_tpm.tsv` includes also novel transcripts. 

- In general, TPMs may vary significantly across different runs, since reported transcripts and thus scaling factor may also differ. I think it makes sense to take a look at counts and grouped (per sample counts). Moreover, current version may not give very accurate results in `transcript_model_tpm.tsv`. So, it makes sense to check `transcript_counts.tsv`.

- Next release (3.4) will contain significant improvement is quantification.

Best
Andrey

**Comment by andrewprzh** [comment]
IsoQuant 3.4 is released, so I suggest to give it a try.

**Comment by andrewprzh** [comment]
I'll close this issue for now, please, re-open if needed.
