### ISSUE TITLE
Increased runtime with IsoQuant 3.4.1

### ISSUE THREAD

**Issue by FabianJetzinger** [ablab/IsoQuant#196]
Other issues have already mentioned increased memory usage in the 3.4 version, but I have also observed some increased runtime and have run a quick comparison on one sample of mouse brain tissue with spike-ins, running with 16 threads and already providing a .db file as reference annotation:

| IsoQuant Version | Data Type | Size of Sample | Elapsed | TotalCPU | MaxMem |
|--------|--------|--------|--------|--------|--------|
| 3.4.1 | PacBio | 4.2GB | 28:15 | 2:33:50 | 6.7GB |
| 3.3.1 | PacBio | 4.2GB | 21:39 | 2:25:58 | 4.6GB |
| 3.4.1 | ONT | 3.9GB | 31:04 | 3:24:14 | 10.5GB |
| 3.3.1 | ONT | 3.9GB | 28:55 | 3:02:26 | 6.9GB |
| 3.4.1 | ONT (subset) | 7.9MB | 04:05 | 09:47 | 2.3GB | 
| 3.3.1 | ONT (subset) | 7.9MB | 02:23 | 03:34 | 1.1GB | 

Find attached the log files. I have not looked into tracking down the source of the issue, but thought at least these results may be of interest to you.

[isoquant_comparison_logs.zip](https://github.com/user-attachments/files/15613647/isoquant_comparison_logs.zip)

**Comment by andrewprzh** [comment]
Dear @FabianJetzinger 

Thanks a lot for the report - this is valuable!
I did a lot of refactoring for 3.4, there might be some side effects that I've missed. I'll get my hands on that.

Best
Andrey

**Comment by andrewprzh** [comment]
@FabianJetzinger 

What appeared to be a larger problem is dramatic increase of RAM consumption in 3.4.1 (not that dramatic on your examples). This issue is fixed in [3.4.2](https://github.com/ablab/IsoQuant/releases/tag/v3.4.2), unfortunately at the expense of longer running time.
You can also use `--high_memory` option to reduce running time, but this, indeed, requires more RAM.

Other than that, it seems like an increase of running time in 3.4.x is possible compared to 3.3.x due to some updated functionality. In the future, I plan to do some performance optimizations, especially with respect to grouping counts with `--read_group`.

I'll close the issue for now, please reopen if you still have some performance issues.

Best
Andrey
