### ISSUE TITLE
Pipeline - combine assembly and reads

### ISSUE THREAD

**Issue by KristinaGagalova** [ablab/IsoQuant#198]
Hi, 

Thank you for working on IsoQuant; it's a great tool.

We are considering alternative approaches for isoform annotation and would like to combine assembled and mapped reads. Do you recommend combining them inside the IsoQuant pipeline or later in our pipeline when we have the 2 outputs from IsoQuant?

Are you considering working on a new feature, maybe one that takes assembled + mapped reads inside IsoQuant? :)

Thank you in advance for the help

**Comment by andrewprzh** [comment]
Hi @KristinaGagalova 

Thank you for the feedback!

So we are not really planning any works on taking assembled sequences. I'd say both approaches are possible, but in my opinion assembled sequences might be "lost" since the will have much lover coverage. Thus, I'd try to run IsoQuant twice and then merge resulting annotation, e.g. using [gffcompare](https://ccb.jhu.edu/software/stringtie/gffcompare.shtml).

You can also run IsoQuant second time providing the output from the first run, for example.
It's hard to say which approach will give the best results, but all them seem viable.

Best
Andrey
