### ISSUE TITLE
Long time to run 80+ samples togather

### ISSUE THREAD

**Issue by yuyun-zhang** [ablab/IsoQuant#210]
Hi Andrey,

Thanks for the amazing tool! I am running over 80 samples simultaneously and plan to obtain a single annotation file. Firstly, I ran 80+ samples togather using chromosome 1, but it has taken 64 hours and not finished yet. So I have split chromosome 1 into 3 parts and am currently running the first part (chr1:1-82,985,474). It has already taken 22 hours but is still not finished. Do you have any suggestions for running 80+ samples together? 

Here is my script: 
```
isoquant.py --reference $genome --complete_genedb --genedb $gtf --bam `ls $dir/*/*chr1-1.3.bam` --data_type nanopore -o annov45_chr1-1.3 -t 32 -l `ls $dir/*/*chr1-1.3.bam | sed 's/.minimap2.cs_sort//g;s/.*\///;s/.bam//'`  
```

Thank you!
Yuyun

**Comment by andrewprzh** [comment]
@yuyun-zhang 

Of course, such large amount of data can take substantial amount of time.
Since each chromosome is processes by a single thread, I don't expect a single chromosome to be processed much faster than all of them (with respect to wall clock time).

What can possibly speed it up is creating a single BAM file via `samtools merge` and giving IsoQuant a single BAM file instead of 80.

Best
Andrey

**Comment by yuyun-zhang** [comment]
Thank you very much! I will creat a single BAM file and rerun it.

**Comment by andrewprzh** [comment]
New [IsoQuant 3.5](https://github.com/ablab/IsoQuant/releases/tag/v3.5.0) should be better in terms of ram consumption, so you can give it a try.

Please, re-open this issue if needed.
