### ISSUE TITLE
Transcript counts don't include novel transcripts

### ISSUE THREAD

**Issue by rsalz** [ablab/IsoQuant#41]
I can't find the counts for the transcripts that are not already known. They show up in the "transcript_models" files, but not in the "transcript_counts". `grep -v 'ENST'` gives me nothing. Am I missing something?

**Comment by andrewprzh** [comment]
Dear @rsalz 

I think the reason is the following:
`.transcript_model_counts.tsv` has counts for `.transcript_models.gtf`, in which transcripts have internal IsoQuant names (e,g. `transcript1.chr1.known`).
To understand which reference id corresponds to this transcript check the respected `reference_transcript_id` field in GTF. 
For example:
```
chr9    IsoQuant        transcript      3003580 3005194 .       +       .       gene_id "ENSMUSG00000096385.7"; transcript_id "transcript_1.chr9.known"; reference_gene_id "ENSMUSG00000096385.7"; reference_transcript_id "ENSMUST00000178077.1"; 
```

If I'm wrong, could you provide your command line and the files you are checking?

Best
Andrey

**Comment by rsalz** [comment]
oh thanks, i see them. I was checking the transcript_counts.tsv file.
